# Originally from bioconda, building against newer openslide builds and for windows.

{% set name = "openslide-python" %}
{% set version = "1.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/openslide/openslide-python/releases/download/v{{ version }}/openslide-python-{{ version }}.tar.gz
  sha256: 998597c5c11c3e05f48632648067cb5fe3884f05cd87d2c23d22c496d17a7fd7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - openslide
  run:
    - pillow
    - python
    - openslide

test:
  imports:
    - openslide

about:
  home: http://openslide.org/
  license: GNU Lesser General Public v2 (LGPLv2)
  license_family: LGPL
  summary: Python interface to OpenSlide

extra:
  recipe-maintainers:
    - bgruening
    - sdvillal
