# Originally from bioconda, building for windows.

{% set name = "openslide-python" %}
{% set version = "1.1.1.post1" %}
{% set commit = "3e9fbca4ea4e729756c6cf76f7bca87e3e8846d1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # until the new version after 1.1.1. gets release, we need to cut from master
  url: https://github.com/openslide/openslide-python/archive/{{ commit }}.zip
  sha256: 998597c5c11c3e05f48632648067cb5fe3884f05cd87d2c23d22c496d17a7fd7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - openslide
  run:
    - pillow
    - python
    - openslide

test:
  imports:
    - openslide

about:
  home: http://openslide.org/
  license: GNU Lesser General Public v2 (LGPLv2)
  license_family: LGPL
  summary: Python interface to OpenSlide

extra:
  recipe-maintainers:
    - bgruening
    - sdvillal
